google.maps.__gjsload__('stats', function(_){'use strict';var h3=function(a,b,c){var d=[];_.zc(a,function(a,c){d.push(c+b+a)});return d.join(c)},i3=function(a,b,c,d){var e={};e.host=window.document.location&&window.document.location.host||window.location.host;e.v=a;e.r=Math.round(1/b);c&&(e.client=c);d&&(e.key=d);return e},uea=function(a){var b={};_.zc(a,function(a,d){b[(0,window.encodeURIComponent)(d)]=(0,window.encodeURIComponent)(a).replace(/%7C/g,"|")});return h3(b,":",",")},vea=function(a,b,c,d){var e=_.R.j[23],f=_.R.j[22];this.ma=a;this.qa=
b;this.ua=null!=e?e:500;this.U=null!=f?f:2;this.W=c;this.V=d;this.R=new _.lj;this.j=0;this.S=_.Ca();j3(this)},j3=function(a){window.setTimeout(function(){wea(a);j3(a)},Math.min(a.ua*Math.pow(a.U,a.j),2147483647))},k3=function(a,b,c){a.R.set(b,c)},wea=function(a){var b=i3(a.qa,a.W,a.V,void 0);b.t=a.j+"-"+(_.Ca()-a.S);a.R.forEach(function(a,d){var e=a();0<e&&(b[d]=Number(e.toFixed(2))+(_.sl()?"":"-if"))});a.ma.j({ev:"api_snap"},b);++a.j},l3=function(a,b,c,d,e){this.V=a;this.ma=b;this.U=c;this.R=d;this.S=
e;this.j=new _.lj;this.W=_.Ca()},m3=function(a,b,c){this.U=b;this.R=a+"/maps/gen_204";this.S=c},n3=function(){this.j=new _.lj},xea=function(a){var b=0,c=0;a.j.forEach(function(a){b+=a.Jr;c+=a.hr});return c?b/c:0},o3=function(a,b,c,d,e){this.W=a;this.ma=b;this.V=c;this.S=d;this.U=e;this.R={};this.j=[]},p3=function(a,b,c,d){this.S=a;_.H.bind(this.S,"set_at",this,this.U);_.H.bind(this.S,"insert_at",this,this.U);this.W=b;this.ma=c;this.V=d;this.R=0;this.j={};this.U()},q3=function(){this.j={}},yea=function(){this.j=
[];this.R=[]},r3=function(a,b,c){this.j=a;this.R=b;this.S=c},zea=function(a,b){a.j.j.push(b);var c=a.R,d=_.pb(b),c=c.j;d in c||(c[d]=0);++c[d];d=a.j;if(d.j.length+d.R.length>a.S){c=a.j;d=c.R;c=c.j;if(!d.length)for(;c.length;)d.push(c.pop());(d=d.pop())&&a.R.remove(d)}},s3=function(a,b){this.V=new r3(new yea,new q3,100);this.R=null;this.Ea=[];this.U=a;_.H.bind(a,"insert_at",this,this.lf);_.H.bind(a,"set_at",this,this.lf);_.H.bind(a,"remove_at",this,this.lf);this.lf();this.j=0;this.va=b;this.S=0},t3=
function(){this.R=_.Ye(_.R);var a;_.T[35]?(a=_.Pe(_.R).j[11],a=null!=a?a:""):a=_.Qx;this.j=new m3(a,_.oi,window.document);new p3(_.ki,(0,_.u)(this.j.j,this.j),_.Nf,!!this.R);a=_.Ue(_.cf());this.W=a.split(".")[1]||a;_.ni&&(this.S=new vea(this.j,this.W,this.ua,this.R));this.ma={};this.V={};this.U={};this.qa={};this.ua=_.Xe()};
l3.prototype.qa=function(a,b){var c=_.sa(b)?b:1;this.j.isEmpty()&&window.setTimeout((0,_.u)(function(){var a=i3(this.ma,this.U,this.R,this.S);a.t=_.Ca()-this.W;var b=this.j;_.mj(b);for(var c={},g=0;g<b.j.length;g++){var h=b.j[g];c[h]=b.va[h]}_.rB(a,c);this.j.clear();this.V.j({ev:"api_maprft"},a)},this),500);c=this.j.get(a,0)+c;this.j.set(a,c)};
m3.prototype.j=function(a,b){var c=b||{},d=_.ck().toString(36);c.src="apiv3";c.token=this.U;c.ts=d.substr(d.length-6);a.cad=uea(c);c=h3(a,"=","&");c=this.R+"?target=api&"+c;this.S.createElement("img").src=c;(d=_.$c.__gm_captureCSI)&&d(c)};n3.prototype.R=function(a,b,c){this.j.set(_.pb(a),{Jr:b,hr:c})};o3.prototype.qa=function(a){this.R[a]||(this.R[a]=!0,this.j.push(a),2>this.j.length&&_.KB(this,this.ua,500))};
o3.prototype.ua=function(){for(var a=i3(this.ma,this.V,this.S,this.U),b=0,c;c=this.j[b];++b)a[c]="1";a.hybrid=+((_.Sk()||!_.Rk())&&_.Rk());this.j.length=0;this.W.j({ev:"api_mapft"},a)};p3.prototype.U=function(){for(var a;a=this.S.removeAt(0);){var b=a.Qq;a=a.timestamp-this.ma;++this.R;this.j[b]||(this.j[b]=0);++this.j[b];if(20<=this.R&&!(this.R%5)){var c={};c.s=b;c.sr=this.j[b];c.tr=this.R;c.te=a;c.hc=this.V?"1":"0";this.W({ev:"api_services"},c)}}};q3.prototype.remove=function(a){a=_.pb(a);var b=this.j;a in b&&(--b[a],b[a]||delete b[a])};r3.prototype.contains=function(a){return!!this.R.j[_.pb(a)]};_.w(s3,_.J);_.t=s3.prototype;_.t.lf=function(){_.G(this.Ea,_.H.removeListener);this.Ea.length=0;var a=this.Ea,b=(0,_.u)(this.eh,this);this.U.forEach(function(c){a.push(_.H.addListener(c.data,"insert",b))});b()};
_.t.eh=function(){var a=this.get("bounds");if(this.get("projection")&&a&&this.R){var b={};this.U.forEach((0,_.u)(function(c){c.data.forEach((0,_.u)(function(c){var d=c.rawData;if(0==(""+d.layer).indexOf(this.R.substr(0,5))&&d.features){c=d.id.length;for(var e=_.uJ(d.id),d=d.features,k=0,n;n=d[k];k++){var p=n.id,q;a:{q=n;if(!q.latLngCached){var r=q.a;if(!r){q=null;break a}var v=new _.M(r[0],r[1]),r=e,v=[v.x,v.y],y=(1<<c)/8388608;v[0]/=y;v[1]/=y;v[0]+=r.ya;v[1]+=r.wa;v[0]/=8388608;v[1]/=8388608;r=new _.M(v[0],
v[1]);v=this.get("projection");q.latLngCached=v&&v.fromPointToLatLng(r)}q=q.latLngCached}q&&a.contains(q)&&(b[p]=n)}}},this))},this));var c=this.V,d;for(d in b)c.contains(d)||(++this.j,zea(c,d));!this.S&&this.j&&(this.S=_.KB(this,this.fp,0))}else _.KB(this,this.eh,1E3)};_.t.fp=function(){this.S=0;this.j&&(_.fm(this.va,"smni",this.j),this.j=0)};_.t.mapType_changed=function(){var a=this.get("mapType");this.R=a&&a.og};_.t.bounds_changed=function(){this.eh()};_.t=t3.prototype;_.t.Vn=function(a,b){var c=new s3(b,a);c.bindTo("mapType",a.__gm);c.bindTo("zoom",a);c.bindTo("bounds",a);c.bindTo("projection",a)};_.t.yo=function(a){a=_.pb(a);this.ma[a]||(this.ma[a]=new o3(this.j,this.W,this.ua,this.R));return this.ma[a]};_.t.wo=function(a){a=_.pb(a);this.V[a]||(this.V[a]=new l3(this.j,this.W,1,this.R));return this.V[a]};_.t.Ef=function(a){if(this.S){this.U[a]||(this.U[a]=new _.XC,k3(this.S,a,function(){return b.Hc()}));var b=this.U[a];return b}};
_.t.vo=function(a){if(this.S){this.qa[a]||(this.qa[a]=new n3,k3(this.S,a,function(){return xea(b)}));var b=this.qa[a];return b}};var Aea=new t3;_.kc("stats",Aea);});
