//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xomorod.Helper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xomorod.Helper.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1m.
        /// </summary>
        public static string _1month {
            get {
                return ResourceManager.GetString("_1month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1w.
        /// </summary>
        public static string _1week {
            get {
                return ResourceManager.GetString("_1week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1y.
        /// </summary>
        public static string _1year {
            get {
                return ResourceManager.GetString("_1year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3d.
        /// </summary>
        public static string _3day {
            get {
                return ResourceManager.GetString("_3day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6m.
        /// </summary>
        public static string _6month {
            get {
                return ResourceManager.GetString("_6month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Xomorod, it&apos;s about using the right tool for the job. If it&apos;s not a nail, we won&apos;t use a hammer. Different teams have different needs, and we let them dictate how they solve their problems, and what technologies they use..
        /// </summary>
        public static string AboutUsDescriptionP1 {
            get {
                return ResourceManager.GetString("AboutUsDescriptionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come join a fun team at a fast growing start-up and be part of the mobile revolution. You will work with some of the best leaders and technical minds in the mobile space..
        /// </summary>
        public static string AboutUsDescriptionP2 {
            get {
                return ResourceManager.GetString("AboutUsDescriptionP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide a highly competitive package with excellent compensation, bonuses, employee benefits, stock options and a friendly, supportive culture..
        /// </summary>
        public static string AboutUsDescriptionP3 {
            get {
                return ResourceManager.GetString("AboutUsDescriptionP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use High Technology.
        /// </summary>
        public static string AboutUsSkill1 {
            get {
                return ResourceManager.GetString("AboutUsSkill1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Windows Applications.
        /// </summary>
        public static string AboutUsSkill2 {
            get {
                return ResourceManager.GetString("AboutUsSkill2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developing Web Projects.
        /// </summary>
        public static string AboutUsSkill3 {
            get {
                return ResourceManager.GetString("AboutUsSkill3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying learning and mobile applications.
        /// </summary>
        public static string AboutUsSkill4 {
            get {
                return ResourceManager.GetString("AboutUsSkill4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number.
        /// </summary>
        public static string Add_phone_number {
            get {
                return ResourceManager.GetString("Add_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave without Captcha..
        /// </summary>
        public static string AlertLeaveWithoutCaptcha {
            get {
                return ResourceManager.GetString("AlertLeaveWithoutCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string An_error_has_occurred {
            get {
                return ResourceManager.GetString("An_error_has_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYZE.
        /// </summary>
        public static string ANALYZE {
            get {
                return ResourceManager.GetString("ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realize your ideas in the form of Android apps at the least possible time.
        /// </summary>
        public static string AndroidService {
            get {
                return ResourceManager.GetString("AndroidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOL.
        /// </summary>
        public static string AOL {
            get {
                return ResourceManager.GetString("AOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        public static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build multi-platform applications with Xamarin technology for iOS and other platforms.
        /// </summary>
        public static string AppleService {
            get {
                return ResourceManager.GetString("AppleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account.
        /// </summary>
        public static string AssociateYourAccount {
            get {
                return ResourceManager.GetString("AssociateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Your Service.
        /// </summary>
        public static string AtYourService {
            get {
                return ResourceManager.GetString("AtYourService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behzad Khosravifar.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Jobs.
        /// </summary>
        public static string BackgroundJobs {
            get {
                return ResourceManager.GetString("BackgroundJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        public static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CafeBazar.
        /// </summary>
        public static string CafeBazar {
            get {
                return ResourceManager.GetString("CafeBazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/cafebazar.png.
        /// </summary>
        public static string CafebazarLogoUrl {
            get {
                return ResourceManager.GetString("CafebazarLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafebazar android market for us products.
        /// </summary>
        public static string CafebazarTitle {
            get {
                return ResourceManager.GetString("CafebazarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cafebazaar.ir/search/?q=xomorod&amp;l=en.
        /// </summary>
        public static string CafebazarXomorodLink {
            get {
                return ResourceManager.GetString("CafebazarXomorodLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha has not valid!.
        /// </summary>
        public static string CaptchaHasNotValid {
            get {
                return ResourceManager.GetString("CaptchaHasNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string Change_account_settings {
            get {
                return ResourceManager.GetString("Change_account_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Change_your_password {
            get {
                return ResourceManager.GetString("Change_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string Click_here_to_Log_in {
            get {
                return ResourceManager.GetString("Click_here_to_Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavanir Blvd, Tabriz, Iran.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Geo Location.
        /// </summary>
        public static string CompanyLocation {
            get {
                return ResourceManager.GetString("CompanyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod Corporation.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string Confirm_Email {
            get {
                return ResourceManager.GetString("Confirm_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacted Successfull..
        /// </summary>
        public static string ContactedSuccessfull {
            get {
                return ResourceManager.GetString("ContactedSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start your next project with us? That&apos;s great!.
        /// </summary>
        public static string ContactUsSubTitle1 {
            get {
                return ResourceManager.GetString("ContactUsSubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a call or send us an email and we will get back to you as soon as possible!.
        /// </summary>
        public static string ContactUsSubTitle2 {
            get {
                return ResourceManager.GetString("ContactUsSubTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To contact the team members can follow them on social networks or via email if you communicate with them..
        /// </summary>
        public static string ContactUsSubTitle3 {
            get {
                return ResourceManager.GetString("ContactUsSubTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create_a_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string CreateLocalLogin {
            get {
                return ResourceManager.GetString("CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_password {
            get {
                return ResourceManager.GetString("Current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug.
        /// </summary>
        public static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Page Speed.
        /// </summary>
        public static string DesktopPageSpeed {
            get {
                return ResourceManager.GetString("DesktopPageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is duplicate!.
        /// </summary>
        public static string DuplicateEmailError {
            get {
                return ResourceManager.GetString("DuplicateEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string Enter_verification_code {
            get {
                return ResourceManager.GetString("Enter_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Enter_your_email {
            get {
                return ResourceManager.GetString("Enter_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a web page URL.
        /// </summary>
        public static string EnterWebpageURL {
            get {
                return ResourceManager.GetString("EnterWebpageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry address is empty!.
        /// </summary>
        public static string EntryUrlEmpty {
            get {
                return ResourceManager.GetString("EntryUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string external_login_removed {
            get {
                return ResourceManager.GetString("external_login_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string Forgot_Password_Confirmation {
            get {
                return ResourceManager.GetString("Forgot_Password_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_your_password {
            get {
                return ResourceManager.GetString("Forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch.
        /// </summary>
        public static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Historical Traffic Trends.
        /// </summary>
        public static string GlobalHistoricalTrafficTrends {
            get {
                return ResourceManager.GetString("GlobalHistoricalTrafficTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Ranking for Today.
        /// </summary>
        public static string GlobalRankingToday {
            get {
                return ResourceManager.GetString("GlobalRankingToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail.
        /// </summary>
        public static string Gmail {
            get {
                return ResourceManager.GetString("Gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. Please check your internet connection!.
        /// </summary>
        public static string InternetError {
            get {
                return ResourceManager.GetString("InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string Invalid_code {
            get {
                return ResourceManager.GetString("Invalid_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string Invalid_login_attempt {
            get {
                return ResourceManager.GetString("Invalid_login_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Historical Traffic Trends.
        /// </summary>
        public static string IranHistoricalTrafficTrends {
            get {
                return ResourceManager.GetString("IranHistoricalTrafficTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Ranking in Iranian websites for Today.
        /// </summary>
        public static string IranRankingToday {
            get {
                return ResourceManager.GetString("IranRankingToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Read?.
        /// </summary>
        public static string IsRead {
            get {
                return ResourceManager.GetString("IsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string Log_in_using_your_0_account {
            get {
                return ResourceManager.GetString("Log_in_using_your_0_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Register.
        /// </summary>
        public static string LoginOrRegister {
            get {
                return ResourceManager.GetString("LoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your web pages fast on all devices..
        /// </summary>
        public static string Make_your_web_pages_fast_on_all_devices {
            get {
                return ResourceManager.GetString("Make_your_web_pages_fast_on_all_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string Manage_external_logins {
            get {
                return ResourceManager.GetString("Manage_external_logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Page Speed.
        /// </summary>
        public static string MobilePageSpeed {
            get {
                return ResourceManager.GetString("MobilePageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Time.
        /// </summary>
        public static string ModifyUtc {
            get {
                return ResourceManager.GetString("ModifyUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Download Now !.
        /// </summary>
        public static string MoreDownloadNow {
            get {
                return ResourceManager.GetString("MoreDownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/myket.png.
        /// </summary>
        public static string MyKetLogoUrl {
            get {
                return ResourceManager.GetString("MyKetLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myket android market for us products.
        /// </summary>
        public static string MyKetTitle {
            get {
                return ResourceManager.GetString("MyKetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://myket.ir/search/xomorod?lang=en.
        /// </summary>
        public static string MyKetXomorodLink {
            get {
                return ResourceManager.GetString("MyKetXomorodLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://news.xomorod.com.
        /// </summary>
        public static string NewsUrl {
            get {
                return ResourceManager.GetString("NewsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured..
        /// </summary>
        public static string No_external_authentication_services_configured {
            get {
                return ResourceManager.GetString("No_external_authentication_services_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... وای! چیزی گم شده است.
        /// </summary>
        public static string Oops_Something_is_missing {
            get {
                return ResourceManager.GetString("Oops_Something_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or the address below.
        /// </summary>
        public static string Or_address_below {
            get {
                return ResourceManager.GetString("Or_address_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook.com.
        /// </summary>
        public static string OutlookCom {
            get {
                return ResourceManager.GetString("OutlookCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSpeed Insights.
        /// </summary>
        public static string PageSpeedInsights {
            get {
                return ResourceManager.GetString("PageSpeedInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Please_check_email_reset_password {
            get {
                return ResourceManager.GetString("Please_check_email_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait . . ..
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many of our projects are open source and free. You can download from GitHub..
        /// </summary>
        public static string PortfolioMoreInfo {
            get {
                return ResourceManager.GetString("PortfolioMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best of our products..
        /// </summary>
        public static string PortfolioSubTitle {
            get {
                return ResourceManager.GetString("PortfolioSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyHeader2_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyHeader2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What information do we collect?.
        /// </summary>
        public static string PrivacyPolicyHeader2_2 {
            get {
                return ResourceManager.GetString("PrivacyPolicyHeader2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the agreement of the site, &quot;{0}&quot; is committed to what be called &quot;Privacy Policy&quot; is considered respect..
        /// </summary>
        public static string PrivacyPolicyP1_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyP1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitments and policies of &quot;{0}&quot; include is:.
        /// </summary>
        public static string PrivacyPolicyP1_2 {
            get {
                return ResourceManager.GetString("PrivacyPolicyP1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are never without your permission, will do not to disclose your private and personal informations, unless under a legal warrant existing for this work..
        /// </summary>
        public static string PrivacyPolicyP1_3 {
            get {
                return ResourceManager.GetString("PrivacyPolicyP1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit any website with the user, specific information is automatically be collected from him. Site {0} is not exempt from this issue and we have access to the following:.
        /// </summary>
        public static string PrivacyPolicyP2_1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyP2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Information about your computer&apos;s IP address (IP Address is based on the numbers automatically when you login to the Web, online service provider by the contract will be assigned to you.).
        /// </summary>
        public static string PrivacyPolicyP2_2 {
            get {
                return ResourceManager.GetString("PrivacyPolicyP2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Source Site URL through which you enter our site. Such as Google, Yahoo or any other website..
        /// </summary>
        public static string PrivacyPolicyP2_3 {
            get {
                return ResourceManager.GetString("PrivacyPolicyP2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Your entry time and elapsed visiting time of &quot;{0}&quot;..
        /// </summary>
        public static string PrivacyPolicyP2_4 {
            get {
                return ResourceManager.GetString("PrivacyPolicyP2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Score.
        /// </summary>
        public static string RankingScore {
            get {
                return ResourceManager.GetString("RankingScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We browse Alexa every day seeking relative intelligence of our performance against our peers. It’s a benchmark that we use to judge our marketing initiatives. As a goal oriented CEO..
        /// </summary>
        public static string RankingSubTitle {
            get {
                return ResourceManager.GetString("RankingSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register_as_a_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string RegisteredLogins {
            get {
                return ResourceManager.GetString("RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string Remember_this_browser {
            get {
                return ResourceManager.GetString("Remember_this_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        public static string Remove_this_0_login_from_your_account {
            get {
                return ResourceManager.GetString("Remove_this_0_login_from_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Completed.
        /// </summary>
        public static string RequestCompleted {
            get {
                return ResourceManager.GetString("RequestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting to Subscribe.
        /// </summary>
        public static string RequestingSubscribe {
            get {
                return ResourceManager.GetString("RequestingSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string Reset_your_password {
            get {
                return ResourceManager.GetString("Reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider.
        /// </summary>
        public static string Select_Two_Factor_Authentications {
            get {
                return ResourceManager.GetString("Select_Two_Factor_Authentications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLang {
            get {
                return ResourceManager.GetString("SelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string Send_verification_code {
            get {
                return ResourceManager.GetString("Send_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xomorod, corporation, software, iOs, windows, tech, news, zomorod, free, .Net, libraries, mobile, applications, android, fast book, website, web, world technology, f56ce249532f51527774.
        /// </summary>
        public static string SeoKeywords {
            get {
                return ResourceManager.GetString("SeoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve got what you need!.
        /// </summary>
        public static string ServiceSubTitle {
            get {
                return ResourceManager.GetString("ServiceSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/bwShonizEn.png.
        /// </summary>
        public static string ShonizLogoUrl {
            get {
                return ResourceManager.GetString("ShonizLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoniz web site.
        /// </summary>
        public static string ShonizTitle {
            get {
                return ResourceManager.GetString("ShonizTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.shoniz.com/.
        /// </summary>
        public static string ShonizUrl {
            get {
                return ResourceManager.GetString("ShonizUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Business Showcase.
        /// </summary>
        public static string ShowcaseClients {
            get {
                return ResourceManager.GetString("ShowcaseClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string Sitemap {
            get {
                return ResourceManager.GetString("Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap of Xomorod.co.
        /// </summary>
        public static string SitemapDescription {
            get {
                return ResourceManager.GetString("SitemapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod Sitemap.
        /// </summary>
        public static string SiteNameSiteMap {
            get {
                return ResourceManager.GetString("SiteNameSiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites Linking In.
        /// </summary>
        public static string SitesLinkingIn {
            get {
                return ResourceManager.GetString("SitesLinkingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave your email and be the first to get updates and news!.
        /// </summary>
        public static string SubscriptEmailSubTitle {
            get {
                return ResourceManager.GetString("SubscriptEmailSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with &lt;strong&gt;{0}&lt;/strong&gt;.
        ///        Please enter a user name for this site below and click the {1} button to finish
        ///        logging in..
        /// </summary>
        public static string SuccessfullyAuthenticatedWithLoginProvider {
            get {
                return ResourceManager.GetString("SuccessfullyAuthenticatedWithLoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email subscribe successfull..
        /// </summary>
        public static string SuccessSubscript {
            get {
                return ResourceManager.GetString("SuccessSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string Thank_confirming_email_Please {
            get {
                return ResourceManager.GetString("Thank_confirming_email_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string The_0_field_is_required {
            get {
                return ResourceManager.GetString("The_0_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string The_0_must_be_at_least__2__characters_long {
            get {
                return ResourceManager.GetString("The_0_must_be_at_least__2__characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string The_new_password_and_confirmation_password_do_not_match {
            get {
                return ResourceManager.GetString("The_new_password_and_confirmation_password_do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string The_password_and_confirmation_password_do_not_match {
            get {
                return ResourceManager.GetString("The_password_and_confirmation_password_do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @xomorod.
        /// </summary>
        public static string TwitterCreator {
            get {
                return ResourceManager.GetString("TwitterCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @xomorod.
        /// </summary>
        public static string TwitterSite {
            get {
                return ResourceManager.GetString("TwitterSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string TwoLetterISOLanguageName {
            get {
                return ResourceManager.GetString("TwoLetterISOLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service.
        /// </summary>
        public static string Unsuccessful_login_with_service {
            get {
                return ResourceManager.GetString("Unsuccessful_login_with_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string Use_a_local_account_to_log_in {
            get {
                return ResourceManager.GetString("Use_a_local_account_to_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string Use_another_service_to_log_in {
            get {
                return ResourceManager.GetString("Use_another_service_to_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Experience.
        /// </summary>
        public static string UserExperience {
            get {
                return ResourceManager.GetString("UserExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via email provider.
        /// </summary>
        public static string Via_email_provider {
            get {
                return ResourceManager.GetString("Via_email_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT&apos;S COMING NEXT?.
        /// </summary>
        public static string WhatsComingNext {
            get {
                return ResourceManager.GetString("WhatsComingNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All software of Xomorod are supported for windows desktop and web platforms.
        /// </summary>
        public static string WindowsService {
            get {
                return ResourceManager.GetString("WindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod.
        /// </summary>
        public static string Xomorod {
            get {
                return ResourceManager.GetString("Xomorod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod Co. multinational technology company specializing in Internet-related services, Include learning, cloud books, tech news and software developing.
        /// </summary>
        public static string XomorodDescription {
            get {
                return ResourceManager.GetString("XomorodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod Corporation has small software company to provide what you need in the field of web applications, Windows, Android and iOS. Most of the application on Xomorod are open source, free to download, and easy to use..
        /// </summary>
        public static string XomorodMoreInfo {
            get {
                return ResourceManager.GetString("XomorodMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod Ranking.
        /// </summary>
        public static string XomorodRanking {
            get {
                return ResourceManager.GetString("XomorodRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our broad tool-set enables us to partner with you to create and integrate custom solutions..
        /// </summary>
        public static string XomorodService {
            get {
                return ResourceManager.GetString("XomorodService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod.
        /// </summary>
        public static string XomorodSiteName {
            get {
                return ResourceManager.GetString("XomorodSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live More Intelligent.
        /// </summary>
        public static string XomorodSlogan {
            get {
                return ResourceManager.GetString("XomorodSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech News, Software Development, Mobile Agent Applications.
        /// </summary>
        public static string XomorodSubject {
            get {
                return ResourceManager.GetString("XomorodSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xomorod Corporation Free Applications &amp; News.
        /// </summary>
        public static string XomorodTitle {
            get {
                return ResourceManager.GetString("XomorodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.xomorod.com.
        /// </summary>
        public static string XomorodUrl {
            get {
                return ResourceManager.GetString("XomorodUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        public static string Yahoo {
            get {
                return ResourceManager.GetString("Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local
        ///        account so you can log in without an external login..
        /// </summary>
        public static string You_not_have_local_username_password_site_Add_local_account {
            get {
                return ResourceManager.GetString("You_not_have_local_username_password_site_Add_local_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string Your_password_changed {
            get {
                return ResourceManager.GetString("Your_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please {0}.
        /// </summary>
        public static string Your_password_reset_Please_0 {
            get {
                return ResourceManager.GetString("Your_password_reset_Please_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string Your_password_set {
            get {
                return ResourceManager.GetString("Your_password_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string Your_phone_number_added {
            get {
                return ResourceManager.GetString("Your_phone_number_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string Your_phone_number_removed {
            get {
                return ResourceManager.GetString("Your_phone_number_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string Your_two_factor_authentication_provider_set {
            get {
                return ResourceManager.GetString("Your_two_factor_authentication_provider_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
